version: '3.8'

services:
  web:
    image: reconectawpp:latest
    build:
      context: https://github.com/jsKahne/reconectawpp.git#main
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "9090:91"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reconecta-whatsapp.rule=Host(`connect.mlgrupo.com.br`)"
        - "traefik.http.routers.reconecta-whatsapp.entrypoints=websecure"
        - "traefik.http.routers.reconecta-whatsapp.tls=true"
        - "traefik.http.routers.reconecta-whatsapp.tls.certresolver=letsencrypt"
        - "traefik.http.services.reconecta-whatsapp.loadbalancer.server.port=91"
        - "traefik.docker.network=reconecta-wpp-traefik"
    environment:
      - REACT_APP_EVOLUTION_API_KEY=${REACT_APP_EVOLUTION_API_KEY}
      - REACT_APP_EVOLUTION_BASE_URL=${REACT_APP_EVOLUTION_BASE_URL}
    networks:
      - reconecta-wpp-traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:91"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  reconecta-wpp-traefik:
    driver: overlay
    attachable: true
    labels:
      - "traefik.enable=true"
      - "com.docker.network.driver.mtu=1450"
