version: '3.8'

services:
  web:
    image: reconecta/whatsapp-frontend:latest
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - REACT_APP_EVOLUTION_API_KEY=${REACT_APP_EVOLUTION_API_KEY}
      - REACT_APP_EVOLUTION_BASE_URL=${REACT_APP_EVOLUTION_BASE_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
